# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Generate docs/data/environments.yaml from resources server configs.

This script imports from update_resource_servers and writes structured YAML
for use in Sphinx docs. Run from repository root:

    python scripts/generate_environments_yaml.py
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml


# Ensure scripts dir is on path for sibling import
_scripts_dir = Path(__file__).resolve().parent
if str(_scripts_dir) not in sys.path:
    sys.path.insert(0, str(_scripts_dir))

from update_resource_servers import get_example_and_training_server_info, normalize_str


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DATA_PATH = REPO_ROOT / "docs" / "data"
ENVIRONMENTS_YAML_PATH = DOCS_DATA_PATH / "environments.yaml"


def _server_to_example_dict(server) -> dict:
    """Convert ServerInfo to dict for example envs."""
    return {
        "name": server.display_name,
        "server_name": server.name,
        "demonstrates": server.get_description_for_example_table(),
        "config_path": server.config_path,
        "config_filename": server.config_filename,
        "readme_path": server.readme_path,
    }


def _server_to_training_dict(server) -> dict:
    """Convert ServerInfo to dict for training envs."""
    meta = server.config_metadata
    dataset = None
    if meta.huggingface_repo_id:
        repo_id = meta.huggingface_repo_id
        dataset = {
            "url": f"https://huggingface.co/datasets/{repo_id}",
            "name": repo_id.split("/")[-1],
        }

    return {
        "name": server.display_name,
        "server_name": server.name,
        "config_path": server.config_path,
        "config_filename": server.config_filename,
        "readme_path": server.readme_path,
        "domain": meta.domain,
        "description": meta.description,
        "value": meta.value,
        "dataset": dataset,
        "train": "train" in set(meta.types),
        "validation": "validation" in set(meta.types),
        "license": meta.license,
        "verified": meta.verified,
        "verified_url": meta.verified_url,
    }


def _build_environments_data(example_servers, training_servers) -> dict:
    """Build YAML-serializable structure with deterministic sort order."""
    example_list = [_server_to_example_dict(s) for s in example_servers]
    example_list.sort(
        key=lambda d: (
            normalize_str(d["name"]),
            normalize_str(d["demonstrates"]),
            normalize_str(d["config_path"]),
            normalize_str(d["readme_path"]),
        )
    )

    training_list = [_server_to_training_dict(s) for s in training_servers]
    training_list.sort(
        key=lambda d: (
            normalize_str(d["name"]),
            normalize_str(d["config_filename"]),
            normalize_str(d.get("domain") or ""),
            normalize_str(d.get("description") or ""),
            normalize_str(d.get("value") or ""),
            d["train"],
            d["validation"],
            normalize_str(d.get("license") or ""),
        )
    )

    return {
        "example": example_list,
        "training": training_list,
    }


def main() -> None:
    """Generate docs/data/environments.yaml from resources server configs."""
    example_servers, training_servers = get_example_and_training_server_info()
    data = _build_environments_data(example_servers, training_servers)

    DOCS_DATA_PATH.mkdir(parents=True, exist_ok=True)

    header = (
        "# Auto-generated by scripts/generate_environments_yaml.py - do not edit manually\n"
        f"# Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\n\n"
    )

    with ENVIRONMENTS_YAML_PATH.open("w") as f:
        f.write(header)
        yaml.dump(
            data,
            f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )


if __name__ == "__main__":
    main()
